port: 8080
mode: debug
emCode: eibpshxfjozidehg
fromEmail: xianren711@qq.com
mysql:
  host:47.92.99.157
  port:3306
  user:root
  password:123456
  db:XrChat
log:
  path:./logs
  level:debug
redis:
  host:47.92.99.157
  port:6379


